name: "Feature Request"
description: "Suggest a new feature or enhancement."
title: "[Feature Request]: "
labels: ["feature request", "enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a feature!**  
        Please fill out the following details to help us understand your request and its impact.

  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Provide a detailed description of the feature, including the problem it solves and how it should work."
      placeholder: "e.g., Dark mode to reduce eye strain in low-light environments."
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: "Benefits"
      description: "Describe the benefits of this feature for users and the application."
      placeholder: "e.g., Enhances user comfort and accessibility."
    validations:
      required: true

  - type: textarea
    id: reference_links
    attributes:
      label: "Reference Links"
      description: "Include any relevant links that provide additional information about the feature."
      placeholder: "e.g., Documentation, articles, existing feature requests."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any additional context, such as technical requirements, constraints, or related issues."
      placeholder: "e.g., Examples from other applications, screenshots, or logs."
    validations:
      required: false
      
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "List any alternative solutions or workarounds that were considered."
      placeholder: "e.g., Browser extensions, third-party applications."
    validations:
      required: false

  - type: textarea
    id: impact_analysis
    attributes:
      label: "Impact Analysis"
      description: "Discuss the potential impact of this feature on existing functionality, users, and workflows."
      placeholder: "e.g., May require updates to existing UI components, potential performance impacts."
    validations:
      required: false
